### PR TITLE
Introspection support

### PR DESCRIPTION
**Pull request by kkatsuyuki**
I implemented introspection using mixins and added an example file for how to use it. I saw
[https://gist.github.com/death/1c5780c5dcf6a838a867d8701969982f](https://gist.github.com/death/1c5780c5dcf6a838a867d8701969982f)
[https://github.com/death/dbus/pull/28](https://github.com/death/dbus/pull/28)

, and I tried to meet what was discussed.
Let me know any comments/requests for introspection addition. I'll consider adjusting my code.

### CODE REVIEW

**Comment by kkatsuyuki** [comment]
I made (i) and (ii) changes.

**Comment by death** [comment]
Thanks kkatsuyuki.

I looked at the code again, and I have some thoughts:

Maybe it would be a good idea for `dbus-object` to inherit from these mixins by default, so that they become an implementation detail (and so their names need not be exported, and the `publish-introspection` example could be fused into the `publish` example). The specification already mentions that DBUS objects form a hierarchy. I don't see why Introspectable should not be implemented by default; if desired there could be a way to override this decision. Do you agree?

Before merging this change I would like to have a different implementation for `relative-path-string`. The current implementation conflates [DBUS object paths](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path) with Common Lisp pathnames/namestrings which are underspecified and not necessarily compatible with DBUS object path syntax. An implementation that performs the necessary string processing without reference to the latter concepts would make sense to me.

The current implementation does not support DBUS object redefinition very well.  This will not prevent me from merging this change, but users should know this and are encouraged to submit patches.

**Comment by kkatsuyuki** [comment]
> Maybe it would be a good idea for dbus-object to inherit from these mixins by default, so that they become an implementation detail (and so their names need not be exported, and the publish-introspection example could be fused into the publish example). The specification already mentions that DBUS objects form a hierarchy. I don't see why Introspectable should not be implemented by default; if desired there could be a way to override this decision. Do you agree?

Though I don't have so much experiences of using dbus, I don't come up with the story that introspectable becomes harmful, so I agree. I'll adjust the code.

> Before merging this change I would like to have a different implementation for relative-path-string. The current implementation conflates [DBUS object paths](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path) with Common Lisp pathnames/namestrings which are underspecified and not necessarily compatible with DBUS object path syntax. An implementation that performs the necessary string processing without reference to the latter concepts would make sense to me.

I also wondered if the implementation was good, so I understand your comment. I'll modify it.

**Comment by kkatsuyuki** [comment]
I've figured out that I simplified the code too much, so let me modify a little bit more.

**Comment by death** [comment]
Thank you kkatsuyuki.

**Pull request merged**
